### ISSUE TITLE
Wrong type of UrlOffset in ClickEvent

### ISSUE THREAD

**Issue by Neonkiller** [edjCase/SendGrid.WebHooks#1]
UrlOffset  in ClickEvent has type string, but in fact json contains object
 "url_offset": {
      "index": 1,
      "type": "html"
    }
thus it can't be parsed to string

**Comment by Gekctek** [comment]
Fixed by #2

**Comment by Gekctek** [comment]
I uploaded a netstandard2/netstandard1.3 nuget package update (version 2.0.0) with your change. Let me know if it doesnt work properly
