### ISSUE TITLE
Unable to parse processed event

### ISSUE THREAD

**Issue by Neonkiller** [edjCase/SendGrid.WebHooks#5]
Web hook like
	{
 "sg_event_id": "IVqXzcSwSMqtCBqkfZX5Gw",
 "sg_message_id": "DhEasnaCSFC0S316nbnQ8Q.filter0611p1iad2-28144-5AAFA6CF-2B.0",
 "send_at": 1521461003.98953,
 "event": "processed",
 "email": "some@email.com",
 "smtp-id": "<xxx.sendgrid.net>",
 "timestamp": 1521460944,
 "CommunicationId": "7627b608-ea32-45e5-8567-e7cd91e3facc"
 },

can not be parsed.
It crashed on parse of  "send_at": 1521461003.98953
as it can not handle double values.
Possible fix:
 - parse all as double or add additional check for double values

**Comment by Gekctek** [comment]
Let me know if the nuget package 2.0.1/new change doesnt fix your issue
